### ISSUE TITLE
Development To-Do

### ISSUE THREAD

**Issue by annikaputt** [hugo-marques/ORFID#2]
import_ORFID_events
- [ ] Function doesn't work without SCD and even when SCD is present the final table isn't populating correctly.

import_ORFID
- [ ] Warning message "no empty line" because the text file doesn't have an end of line marker or a space in it.
- [ ] Warning message about parsing when the first line of data doesn't have the full number of columns.

start/stop function
- [ ] Files don't actually have "reader started" data
